name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - wget http://dl.google.com/android/android-sdk_r18-linux.tgz

   - tar -zxf android-sdk_r18-linux.tgz

  

  - export ANDROID_HOME=~/builds/[github username]/[your project name]/android-sdk-linux

  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  



  - android update sdk --filter 1,2,9 --no-ui --force
    - uses: actions/checkout@v3
    - name: configure

      run: bash ./config.sh

    - name: build
      run: bash ./setup.sh
      


      


      
   

